### ISSUE TITLE
Stack logos

### ISSUE THREAD

**Issue by belauzas** [belauzas/quasar-project#9]
Gigabyte technologies
Nvidia
vmware
amd

**Comment by CopernicAI** [comment]
examples: 
Amd Epyc: [https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vhv.rs%2Fviewpic%2FhobwbJh_logo-of-the-amd-epyc-soc-cpu-epyc%2F&psig=AOvVaw2KwJB_p2ksx3m1pD4jwiKh&ust=1597926354950000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCMDGjduhp-sCFQAAAAAdAAAAABAD](url)
AMD: [https://icon2.cleanpng.com/20180812/aos/kisspng-logo-advanced-micro-devices-laptop-ryzen-radeon-amd-logo-nasdaq-semiconductors-logo-5b6fddfb3cf402.4940582615340579792497.jpg](url)
Nvidia: [https://banner2.cleanpng.com/20180520/pti/kisspng-nvidia-logo-geforce-intel-graphics-processing-unit-5b018ba9df5832.0931976215268279459148.jpg](url)
Gigabyte: [https://cutewallpaper.org/21/gigabyte-logos/Techno-Business-Computer-B.V..png](url)
Nvidia RTX: [https://www.nvidia.com/content/dam/en-zz/Solutions/gfn/webassets/memberships/icon-nvidia-rtx-d@2x.png](url)
VMWare: [https://logos-download.com/wp-content/uploads/2016/09/VMware_logo.png](url)
wmvare vsphere: [https://toppng.com/uploads/preview/vmware-logo-11551053451eoqivya6x7.png](url)
